name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]  # 최신 Node.js 버전 포함

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # v3 버전으로 업데이트

      - name: Set up Node.js
        uses: actions/setup-node@v3  # v3 버전으로 업데이트
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        working-directory: ./my-react-app
        run: |
          docker build -t my-react-app:latest .
          docker tag my-react-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

      - name: Push Docker image
        working-directory: ./my-react-app
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
